steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},STORAGE_BUCKET=${_STORAGE_BUCKET},MODELS_BUCKET=${_MODELS_BUCKET}'

# Substitute variables
substitutions:
  _IMAGE_NAME: 'visionflow-pro'
  _SERVICE_NAME: 'visionflow-api'
  _REGION: 'us-central1'
  _DATABASE_URL: 'postgresql://user:password@/visionflow'
  _STORAGE_BUCKET: 'visionflow-storage'
  _MODELS_BUCKET: 'visionflow-models'

# Images to push
images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'

# Timeout
timeout: '1800s'